
version: "3.9"

services:
  front:
    image: solarflare:0.1.0
#    stdin_open: true
    #volumes:
    #  - .:/app/
       #- ./configs/nginx/solarflare.conf:/etc/nginx/sites-available/nginx.conf
       #- ./configs/nginx/solarflare.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - SKIP_PREFLIGHT_CHECK=true

volumes:
  node_modules: